title: Mi sitio web sencillo
description: Pagina creada con Jekyll y con GitHub pages
remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
